### ISSUE TITLE
Add range.

### ISSUE THREAD

**Issue by aviwad** [arjun-dureja/ModernSlider#1]
I want a slider mapping to values 5-100. Yours takes a value binding double that maps to 0 to 100. This is not practical. Please add the in argument that the original `Slider{}` has, for feature parity. Thank you. Great project btw love the UI.

**Comment by arjun-dureja** [comment]
Thanks for the suggestion! I've added a customizable `range` param in the latest version https://github.com/arjun-dureja/ModernSlider/releases/tag/v1.0.1
